### ISSUE TITLE
Can't find account info file for account cloned from cluster 

### ISSUE THREAD

**Issue by nathanleclaire** [metaplex-foundation/amman#45]
OSX, M1

my config:

```
module.exports = {
    validator: {
        accountsCluster: "https://api.mainnet-beta.solana.com",
        accounts: [
            {
                label: "Goki Smart Wallet Program",
                accountId: "GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH",
                executable: true,
            },
        ],
    },
};
```

blows up with an error on `amman start`

```
Loading config from /Users/nathanleclaire/worknet/.ammanrc.js
Running validator with 0 custom program(s) and 1 remote account(s) preloaded
Launching new solana-test-validator with programs predeployed and ledger at /var/folders/ps/6j4p5ftd2jq3rqc886kx2l7m0000gn/T/amman-ledger
Saving account GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH from cluster https://api.mainnet-beta.solana.com
Saving executable data for GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH from cluster https://api.mainnet-beta.solana.com
Error: Can't find account info file for account GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH cloned from cluster https://api.mainnet-beta.solana.com! 
Make sure the account exists locally or on that cluster and try again.
    at processAccounts (/Users/nathanleclaire/.nvm/versions/node/v16.15.0/lib/node_modules/@metaplex-foundation/amman/dist/validator/process-accounts.js:29:23)
    at async buildSolanaValidatorArgs (/Users/nathanleclaire/.nvm/versions/node/v16.15.0/lib/node_modules/@metaplex-foundation/amman/dist/validator/solana-validator.js:46:69)
    at async initValidator (/Users/nathanleclaire/.nvm/versions/node/v16.15.0/lib/node_modules/@metaplex-foundation/amman/dist/validator/init-validator.js:50:136)
    at async handleStartCommand (/Users/nathanleclaire/.nvm/versions/node/v16.15.0/lib/node_modules/@metaplex-foundation/amman/dist/cli/commands/start.js:36:9)
    at async main (/Users/nathanleclaire/.nvm/versions/node/v16.15.0/lib/node_modules/@metaplex-foundation/amman/dist/cli/amman.js:154:34)
Rerun `amman --help` for more information
```

**Comment by nathanleclaire** [comment]
ok, the `solana` command isn't saving the account correctly. this is with solana cli `1.18.14` FWIW

```
$ solana --version
solana-cli 1.8.14 (src:9c01d90c; feat:1006352700)

$ solana account 5k7J7X7XZmSHiosxf41uw5jz98NDTZeKpxaJhP1QquTy -u https://api.mainnet-beta.solana.com -o /Users/nathanleclaire/amman/.amman/accounts/5k7J7X7XZmSHiosxf41uw5jz98NDTZeKpxaJhP1QquTy.json --output json
... outputs JSON to terminal ...

$ ls /Users/nathanleclaire/amman/.amman/accounts/5k7J7X7XZmSHiosxf41uw5jz98NDTZeKpxaJhP1QquTy.json
ls: /Users/nathanleclaire/amman/.amman/accounts/5k7J7X7XZmSHiosxf41uw5jz98NDTZeKpxaJhP1QquTy.json: No such file or directory
```

**Comment by nathanleclaire** [comment]
aha ... upgrading to `solana` cli version `1.10.24` fixed it... maybe amman could do a version check in the future ... but my issue is resolved

**Comment by jshiohaha** [comment]
phew - thanks @nathanleclaire for the issue & comments. this helped me troubleshoot the same issue 😅 upgrading from `solana-cli 1.9.0` to the latest version at the time (`1.10.32`) worked for me as well.
